### ISSUE TITLE
It look like  the video is not loading in Api 19

### ISSUE THREAD

**Issue by gohugo** [ct7ct7ct7/Android-VimeoPlayer#10]
On api 28 the video is loading but on api 19 the video is stock on loading screen

**Comment by gohugo** [comment]
i tested with api 21 and it also working

**Comment by gohugo** [comment]
so the  problem is only api 19 and bellow

**Comment by crearo** [comment]
It doesn't work for that probably because `evaluateJavascript` was only introduced in KitKat 19.

**Comment by ct7ct7ct7** [comment]
I have no idea what caused the problem

**Comment by patrickpissurno** [comment]
So it seems to be no way of back-porting this library to API 16 (or API 17), isn't it?

The reason why would be just the lack of ```evaluateJavascript``` or also something else? Because while searching for a workaround [I got to this](https://medium.com/@elye.project/making-android-interacting-with-web-app-921be14f99d8).

You can inject javascript into the webview with ```loadUrl``` and get the result back with the help of the ```addJavascriptInterface``` method. Sure it would be a bit cumbersome to do, but nice to have.
